#!/hint/bash

## this script fragment tunes kernel config during prepare(), it runs from src/linux.../ before
## makeolddefconfig is called

# Disable localversion_auto so kernel version tracks package version
scripts/config --disable LOCALVERSION_AUTO

## Disallow unprivileged namespaces
#scripts/config --disable USER_NS_UNPRIVILEGED

# enable ACPI debugging
scripts/config --enable CONFIG_ACPI_DEBUG

# enable scheduler autogrouping
scripts/config --enable CONFIG_SCHED_AUTOGROUP

# set a larger kernel log buffer (18 -> 256KB)
scripts/config --set-val CONFIG_LOG_BUF_SHIFT 18

# enable EFI var access
scripts/config --enable CONFIG_EFI_VARS

# use fq_pie by default
scripts/config --module CONFIG_NET_SCH_FQ_CODEL
scripts/config --enable CONFIG_NET_SCH_PIE
scripts/config --enable CONFIG_NET_SCH_FQ_PIE
scripts/config --disable CONFIG_DEFAULT_FQ_CODEL
scripts/config --enable CONFIG_DEFAULT_FQ_PIE
scripts/config --set-str CONFIG_DEFAULT_NET_SCH "fq_pie"

## use tcp_bbr by default; uncomment if not using bbr2
#scripts/config --module CONFIG_TCP_CONG_CUBIC
#scripts/config --enable CONFIG_TCP_CONG_BBR
#scripts/config --disable CONFIG_DEFAULT_CUBIC
#scripts/config --enable CONFIG_DEFAULT_BBR
#scripts/config --set-str CONFIG_DEFAULT_TCP_CONG "bbr"

# use tcp_bbr2 by default
scripts/config --module CONFIG_TCP_CONG_CUBIC
scripts/config --module CONFIG_TCP_CONG_BBR
scripts/config --enable CONFIG_TCP_CONG_BBR2
scripts/config --disable CONFIG_DEFAULT_CUBIC
scripts/config --enable CONFIG_DEFAULT_BBR2
scripts/config --set-str CONFIG_DEFAULT_TCP_CONG "bbr2"

# enable multigen LRU by default
scripts/config --enable CONFIG_LRU_GEN
scripts/config --disable LRU_GEN_STATS
scripts/config --set-val NR_LRU_GENS 7
scripts/config --set-val TIERS_PER_GEN 4
scripts/config --enable CONFIG_LRU_GEN_ENABLED

# AMD pstate
scripts/config --enable CONFIG_X86_AMD_PSTATE

# bake in s0ix debugging parameters so we get useful problem reports re: suspend
scripts/config  --enable CONFIG_CMDLINE_BOOL \
                --set-str CONFIG_CMDLINE "makepkgplaceholderyolo" \
                --disable CMDLINE_OVERRIDE

# HACK: forcibly fixup CONFIG_CMDLINE here as using scripts/config mangles escaped quotes
sed -i 's#makepkgplaceholderyolo#pm_debug_messages amd_pmc.enable_stb=1 amd_pmc.dyndbg=\\"+p\\" acpi.dyndbg=\\"file drivers/acpi/x86/s2idle.c +p\\"#' .config

# Note the double escaped quotes above, sed strips one; the final result in .config needs to contain single slash
# escaped quotes (eg: `CONFIG_CMDLINE="foo.dyndbg=\"+p\""`) to avoid dyndbg parse errors at boot. This is impossible
# with the current kernel config script.

